### ISSUE TITLE
If cannot fetch previous version, generate 1.0.0

### ISSUE THREAD

**Issue by bahmutov** [bahmutov/semantic-action#7]
For example, if `build.json` is missing, `url-to-sha` should return default value and it should set new version to `1.0.0`
```
[Travis Deploy Once]: Success at attempt 1. All 1 jobs passed.
semantic-action ERR! pre Failed to determine new version.
semantic-action ERR! pre Response code 404 (Not Found) HTTPError: Response code 404 (Not Found)
semantic-action ERR! pre     at stream.catch.then.data (/home/travis/build/bahmutov/test-semantic-deploy-with-now/node_modules/got/index.js:182:13)
semantic-action ERR! pre     at <anonymous>
semantic-action ERR! pre     at process._tickCallback (internal/process/next_tick.js:188:7)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```

**Comment by bahmutov** [comment]
Done, the release plugin has to return `{type: 'initial'}` to trigger 1.0.0 release
